# Generated by Django 4.2.5 on 2023-09-21 03:36

from django.db import migrations, models
import django.db.models.deletion
import django_ulid.models
import ulid.api.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=ulid.api.api.Api.new, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_v1.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=ulid.api.api.Api.new, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("user_id", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_v1.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=ulid.api.api.Api.new, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(null=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="products_variants", to="api_v1.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=ulid.api.api.Api.new, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.CharField(max_length=30)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="api_v1.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.ManyToManyField(
                related_name="products_reviews", to="api_v1.review"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="variants",
            field=models.ManyToManyField(
                related_name="products_variants", to="api_v1.variant"
            ),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=ulid.api.api.Api.new, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.CharField(max_length=30, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api_v1.product"
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api_v1.variant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=ulid.api.api.Api.new, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("object_id", django_ulid.models.ULIDField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="api_v1_imag_content_895a85_idx",
                    )
                ],
            },
        ),
    ]
