# Generated by Django 4.2.5 on 2023-09-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0007_alter_category_id_alter_image_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="url",
            new_name="image_url",
        ),
    ]
