# Generated by Django 4.2.6 on 2023-10-05 11:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.UUIDField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=30)),
                ("url", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner", models.UUIDField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=350)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("slug", models.CharField(max_length=30, unique=True)),
                ("logo_img_url", models.CharField(max_length=350, null=True)),
                ("banner_img_url", models.CharField(max_length=350, null=True)),
                ("website", models.CharField(null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("business_license_number", models.CharField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="store_members", to="api_v1.member"
                    ),
                ),
                (
                    "socials",
                    models.ManyToManyField(
                        related_name="store_socials", to="api_v1.social"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="social",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api_v1.store"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api_v1.store"
            ),
        ),
    ]
