# Generated by Django 4.2.5 on 2023-10-04 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Rating must be at least 1'), django.core.validators.MaxValueValidator(limit_value=5, message='Rating must be at most 5')]),
        ),
    ]
