# Generated by Django 4.2.5 on 2023-10-04 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observation', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('active_comments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('active_reviews', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Rating must be at least 1'), django.core.validators.MaxValueValidator(limit_value=5, message='Rating must be at most 5')]),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.comment'),
        ),
    ]
